config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos

  root 'videos#index'

  get 'about', to: 'videos#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :videos
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  mount_uploader :file, VideoUploader

  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("title LIKE ?", "%#{search}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
    if params[:search]
      @videos = Video.search(params[:search]).order("created_at DESC")
    else
      @videos = Video.all.order('created_at DESC')
    end
  
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = current_user.videos.build
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = current_user.videos.build(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/_navigation.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
}

.navbar {
  overflow: hidden;
  background-color: #333;
}

.navbar a {
  float: left;
  font-size: 16px;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

.dropdown {
  float: left;
  overflow: hidden;
}

.dropdown .dropbtn {
  font-size: 16px;
  border: none;
  outline: none;
  color: white;
  padding: 14px 16px;
  background-color: inherit;
  font-family: inherit;
  margin: 0;
}

.navbar a:hover, .dropdown:hover .dropbtn {
  background-color: red;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  float: none;
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
  text-align: left;
}

.dropdown-content a:hover {
  background-color: #ddd;
}

.dropdown:hover .dropdown-content {
  display: block;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}

.topnav-right {
  float: right;
}


</style>
</head>

<body>

<div class="navbar">
  <%= link_to "Home", root_path, class: "active" %>
  <!-- <a href="/">Home</a> -->
  <%= link_to "About", about_path, class: "active" %>
  <%= link_to 'New Video', new_video_path %>


  <div class="topnav-right">

  <% if user_signed_in? %>

  <li><%= link_to "Account", edit_user_registration_path %></li>
  <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>

  <% else %>

  <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>

  <% end %>

  </div>

</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TV Show Intros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render 'layouts/navigation' %>
     <% flash.each do |name, msg| %>
                      <%= content_tag(:div, msg, class: "alert alert-info") %>
                    <% end %>
     <%= yield %>
  </body>
</html>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true, html: { multipart: true }) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :video_title %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file, id: :video_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/about.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  margin: 8px;
}

.about-section {
  padding: 50px;
  text-align: center;
  background-color: #474e5d;
  color: white;
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}

img {
  display: block;
  margin-left: auto;
  margin-right: auto;
}
</style>


<div class="about-section">
  <h1>About Us</h1>
  <p>We show all different TV Show intros out there</p>

</div>

<h2 style="text-align:center">Our Team</h2>
<div class="row">
  <div class="column">
    <div class="card">
      <img src="https://bit.ly/2VEKVsa" alt="Joe" style="width:30%">
      <div class="container">
        <h2>Joe Goldberg</h2>
        <p class="title">Book Specialist and Customer Assitant and Anavrin</p>
        <p>Book fanatic by day, serial killer by night.</p>
        <p>joe_goldberg@email.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="https://bit.ly/3co8uLP" alt="Mike" style="width:33.5%">
      <div class="container">
        <h2>Mike Ross</h2>
        <p class="title">Junior Partner at Pearson Specter Litt</p>
        <p>A Lawyer that hasn't got a Law Degree</p>
        <p>mikeross@pearsonspecterlitt.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>

  <div class="column">
    <div class="card">
      <img src="https://bit.ly/38c1fTP" alt="John" style="width:32.5%">
      <div class="container">
        <h2>Don Draper</h2>
        <p class="title">Senior Partner and Head of Creative at Sterling Cooper & Partners</p>
        <p>Real name is Richard Whitman</p>
        <p>don.draper@sc.com</p>
        <p><button class="button">Contact</button></p>
      </div>
    </div>
  </div>
</div>

app/views/videos/edit.html.erb
<div class="center1">
  <h2 class="title center2 animated"></h2>
  <div class="center2 pinRC">
    <body>
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>


</body>
<a class="pinR">
</a>
</div>
<div class="pinC animated">

<p>
</p>
</div>
</div>
<body>
<script>
jQuery.fn.reverse = [].reverse;

var PIN = "1248";

function confirm(pC, pRC, pI, t) {
  var val = pI.attr('pin');
  if (typeof val !== 'undefined' && typeof val !== 'null' && val !== '' && val.length === 4 && val === PIN) {
    pC.removeClass("bounceInUp");
    pC.addClass("bounceOutDown");
    t.removeClass("rubberBand");
    setTimeout(function() {
      pC.hide();
      pRC.fadeIn();
      t.addClass("rubberBand").html('Pin correct! You can edit a Video');
    }, 500);
  } else {
    pC.removeClass("bounceInUp").removeClass("shake");
    setTimeout(function() {
      pC.addClass("shake");
    }, 200);
    pI.children(".pinpart").removeClass("active").removeClass("rubberBand");
    pI.attr('pin', '');
  }
}

$(document).ready(function() {
  var pC = $(".pinC");
  var pRC = $(".pinRC");
  var pR = $(".pinR");
  var pI;
  var t = $(".title");



  var xa = 0;
  for (var x = 1; x <= 9; x++) {
    var x2;
    var y1_2 = '',
    y2_2 = '',
    y3_2 = '',
    y4_2 = '';
    if (x > 1) {
      if (x === 2) {
        x2 = x - 1;
      } else {
        x2 = (x) * 3 - (5 - xa);
      }
      if (x === 7) {
        xa = 1;
      }

      var y1 = x2 + 96,
      y2 = y1 + 1,
      y3 = y2 + 1;
      if (x === 7 || x === 9) {
        var y4 = y3 + 1;
        y4_2 = String.fromCharCode(y4);
      }

      y1_2 = String.fromCharCode(y1),
      y2_2 = String.fromCharCode(y2),
      y3_2 = String.fromCharCode(y3);
    }
    var eLe = $('<div class="pinB" nr="'+x+'"><span class="pin_T">'+x+'</span><span class="pin_t">'+y1_2+y2_2+y3_2+y4_2+'</span></div>');
    pC.append(eLe);
  }
  var eLe = $('<div class="pinB input animated" pin=""><span class="pinpart animated"></span><span class="pinpart animated"></span><span class="pinpart animated"></span><span class="pinpart animated"></span></div><div class="pinB" nr="0"><span class="pin_T">0</span><span class="pin_t"></span></div><div class="pinB delete"><span class="pin_T">[X]</span></div>');
  pC.append(eLe);
  pI = pC.find(".pinB.input");
  $(".pinB:not(.empty):not(.input):not(.delete)").on('click', function() {
    var val1 = pI.html();
    var val2 = pI.attr('pin');
    pI.children(".pinpart").removeClass("rubberBand");
    if (val2.length < 4) {
      var vx = 0;
      pI.children(".pinpart").each(function() {
        if (val2.length === vx) {
          $(this).addClass("active").addClass("rubberBand");
        }
        vx++;
      });
      // pI.html(val1 + "* ");
      pI.attr('pin', val2 + $(this).attr("nr"));
      if (pI.attr('pin').length === 4) {
        pI.removeClass("tada").removeClass("jello");
        setTimeout(function() {
          pI.addClass("tada");
          setTimeout(function() {
            pI.removeClass("tada");
          }, 600);
        }, 200);
      }
    } else {
      pI.removeClass("jello");
      setTimeout(function() {
        pI.addClass("jello");
      }, 200);
    }
    setTimeout(function() {
      pI.children(".pinpart").removeClass("rubberBand");
    }, 400);
  });
  $(".pinB.delete").on('click', function() {
    var val1 = pI.html();
    var val2 = pI.attr('pin');
    pI.removeClass("jello");
    pI.children(".pinpart").removeClass("rubberBand");
    if (typeof val2 !== 'undefined' && typeof val2 !== 'null' && val2 !== '') {
      var vx = 4;
      pI.children(".pinpart").reverse().each(function() {
        if (val2.length === vx) {
          $(this).removeClass("active").addClass("rubberBand");
        }
        vx--;
      });
      // pI.html(val1.slice(0, val1.length - 2));
      pI.attr('pin', val2.slice(0, val2.length - 1));
    }
    setTimeout(function() {
      pI.children(".pinpart").removeClass("rubberBand");
    }, 400);
  });
  pI.on('click', function() {
    pI.children(".pinpart").removeClass("rubberBand");
    confirm(pC, pRC, pI, t);
  });

  pR.on('click', function() {
    pRC.hide();
    pI.children(".pinpart").removeClass("active").removeClass("rubberBand");
    pI.attr('pin', '');
    t.html('Enter Pin to edit a Video');
    pC.removeClass("bounceOutDown");
    pC.addClass("bounceInUp");
    pC.show();
  });
  pR.click();
});
</script>
</body>

<body>
<style>

body {
  margin: 0;
}

.center1 {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-38%, -50%);
}
.center2 {
  text-align: center;
}

.pinRC {
  display: none;
}

.pinC {
  display: block;
  position: relative;
  width: 255px;
  height: 200px;
}
.pinC > .pinB {
  position: relative;
  float: left;
  width: calc(200px / 3);
  height: calc(200px / 3);
  text-align: center;
  line-height: 3;
  -webkit-transition: all 0.2s ease;
  -moz-transition: all 0.2s ease;
  -o-transition: all 0.2s ease;
  transition: all 0.2s ease;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
.pinC > .pinB:not(.empty) {
  background-color: #dcdcdc;￼
  border: 2px solid #ffffff;
}
.pinC > .pinB:not(.empty):hover {
  /*     border: 2px dotted #fefefe; */
  cursor: pointer;
}
.pinC > .pinB:not(.empty)::before {
  content: " ";
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(100, 100, 100, 0);
  -webkit-transition: all 0.4s ease;
  -moz-transition: all 0.4s ease;
  -o-transition: all 0.4s ease;
  transition: all 0.4s ease;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
.pinC > .pinB:not(.empty):active::before {
  background-color: rgba(200, 200, 200, 0.45);
}
.pinC > .pinB > .pin_T {
  position: absolute;
  width: 100%;
  left: 0%;
  height: 100%;
}
.pinC > .pinB > .pin_t {
  font-size: 75%;
  position: absolute;
  bottom: -5px;
  left: 50%;
  color: darkgrey;
  transform: translate(-50%, 0);
}

.pinC > .pinB.input > .pinpart {
  border: 2px solid #000000;
  border-radius: 50%;
  float: left;
  background-color: transparent;
  width: 7px;
  height: 10px;
  position: relative;
  top: calc(50% - 5px);
  margin-left: 4.5px;
  background-color: rgba(100, 100, 100, 0);
  -webkit-transition: all 0.4s ease;
  -moz-transition: all 0.4s ease;
  -o-transition: all 0.4s ease;
  transition: all 0.4s ease;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
.pinC > .pinB.input > .pinpart.active {
  background-color: #000000;
}

.confirmed {
  animation: removec ease-out 1s;
  animation-iteration-count: 1;
  transform-origin: 0% 50%;
  animation-fill-mode: forwards;
  /*when the spec is finished*/
  -webkit-animation: removec ease-out 1s;
  -webkit-animation-iteration-count: 1;
  -webkit-transform-origin: 0% 50%;
  -webkit-animation-fill-mode: forwards;
  /*Chrome 16+, Safari 4+*/
  -moz-animation: removec ease-out 1s;
  -moz-animation-iteration-count: 1;
  -moz-transform-origin: 0% 50%;
  -moz-animation-fill-mode: forwards;
  /*FF 5+*/
  -o-animation: removec ease-out 1s;
  -o-animation-iteration-count: 1;
  -o-transform-origin: 0% 50%;
  -o-animation-fill-mode: forwards;
  /*Not implemented yet*/
  -ms-animation: removec ease-out 1s;
  -ms-animation-iteration-count: 1;
  -ms-transform-origin: 0% 50%;
  -ms-animation-fill-mode: forwards;
  /*IE 10+*/
}

@keyframes removec {
  0% {
    opacity: 1;
    transform: translate(0px, 0px) scaleX(1.00);
  }
  20% {
    opacity: 1;
    transform: translate(0px, 10px) scaleX(1.00);
  }
  25% {
    transform: translate(0px, 0px) scaleX(1.00);
  }
  27% {
    opacity: 0;
    transform: translate(0px, 0px) scaleX(0.00);
  }
  100% {
    opacity: 0;
    transform: translate(0px, 0px) scaleX(0.00);
  }
}

@-moz-keyframes removec {
  0% {
    opacity: 1;
    -moz-transform: translate(0px, 0px) scaleX(1.00);
  }
  20% {
    opacity: 1;
    -moz-transform: translate(0px, 10px) scaleX(1.00);
  }
  25% {
    -moz-transform: translate(0px, 0px) scaleX(1.00);
  }
  27% {
    opacity: 0;
    -moz-transform: translate(0px, 0px) scaleX(0.00);
  }
  100% {
    opacity: 0;
    -moz-transform: translate(0px, 0px) scaleX(0.00);
  }
}

@-webkit-keyframes removec {
  0% {
    opacity: 1;
    -webkit-transform: translate(0px, 0px) scaleX(1.00);
  }
  20% {
    opacity: 1;
    -webkit-transform: translate(0px, 10px) scaleX(1.00);
  }
  25% {
    -webkit-transform: translate(0px, 0px) scaleX(1.00);
  }
  27% {
    opacity: 0;
    -webkit-transform: translate(0px, 0px) scaleX(0.00);
  }
  100% {
    opacity: 0;
    -webkit-transform: translate(0px, 0px) scaleX(0.00);
  }
}

@-o-keyframes removec {
  0% {
    opacity: 1;
    -o-transform: translate(0px, 0px) scaleX(1.00);
  }
  20% {
    opacity: 1;
    -o-transform: translate(0px, 10px) scaleX(1.00);
  }
  25% {
    -o-transform: translate(0px, 0px) scaleX(1.00);
  }
  27% {
    opacity: 0;
    -o-transform: translate(0px, 0px) scaleX(0.00);
  }
  100% {
    opacity: 0;
    -o-transform: translate(0px, 0px) scaleX(0.00);
  }
}

@-ms-keyframes removec {
  0% {
    opacity: 1;
    -ms-transform: translate(0px, 0px) scaleX(1.00);
  }
  20% {
    opacity: 1;
    -ms-transform: translate(0px, 10px) scaleX(1.00);
  }
  25% {
    -ms-transform: translate(0px, 0px) scaleX(1.00);
  }
  27% {
    opacity: 0;
    -ms-transform: translate(0px, 0px) scaleX(0.00);
  }
  100% {
    opacity: 0;
    -ms-transform: translate(0px, 0px) scaleX(0.00);
  }
}
</style>
</body>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <%= link_to 'New Video', new_video_path %> -->

<h1>
  TV Show Intros
</h1>

<body>

  <p></p>

  <input type="text" id="myInput" onkeyup="ContactsearchFX()" placeholder="Search Intros">

  <p></p>

</body>

<script type="text/javascript">
  window.onload = function() {
    var rows = document.querySelectorAll('tr:not(.header)');

    for (var i = 0; i < rows.length; i++) {
      //rows[i].style.display = 'none';
    }
  }

  function ContactsearchFX() {
    var input, filter, table, tr, td, i;

    input = document.getElementById("myInput");

    filter = input.value.toUpperCase();
    table = document.getElementById("myTable");
    tr = table.getElementsByTagName("tr");
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[0];
      if (td) {
        if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";

        }
      }
    }

    var rows = document.querySelectorAll('tr:not(.header)');

    if (input.value.length == 0) {
      for (var i = 0; i < rows.length; i++) {
        rows[i].style.display = 'none';
      }
    }
  }
</script>

<table id="myTable">
  <thead>
    <tr class="header">
      <th>Title</th>
      <!--<th>File</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
    <tr>
      <td><%= video.title %></td>
      <!-- <td><%= video.file %></td> -->
      <% if user_signed_in? %>
      <td><%= link_to 'Show', video %></td>
      <td><%= link_to 'Edit', edit_video_path(video) %></td>
      <!-- <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      <% else %>
      <td><%= link_to 'Show', video %></td>

      <% end %>
      <% end %>
    </tr>
  </tbody>
</table>

<br>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>File:</strong>
  </p>
<p>

  <video controls width="550" height="320" src="<%= @video.file %>"></video>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>